---
title: "Tarea 1"
author: "Ingrid Fonseca C03042-Esaú Ramirez C06348"
date: "2024-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
echo=FALSE
#install.packages("ggthemes")
#install.packages("httr")
#install.packages("dplyr")
library(dplyr)
library(tidyverse)
library(ggplot2)
library(httr)
library(readr)
library(ggthemes)
library(httr)
#library(gridExtra)
```



```{r}
#url <- "https://github.com/inad1104/Tarea1-EstadisticaII/blob/df9683b260512959742a705476ac5998f7d8c1a6/BaseSalarios.csv"
#BaseSalarios <- read_csv(url, show_col_types = FALSE)
#BaseSalarios <- read_csv("C:/Users/ingri/Downloads/BaseSalarios.csv")
BaseSalarios <- read_csv("/Users/esaurm27/Desktop/Tarea1-EstadisticaII/BaseSalarios.csv")

```

```{r}
BaseSalarios$Sexo <- ifelse(BaseSalarios$Sexo == 1, 'hombre', 'mujer')
BaseSalarios$`U. Salario` <- floor(BaseSalarios$`U. Salario`/1000)
```

```{r}
media_salario_mujeres <- mean(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'mujer'])
media_salario_hombres <- mean(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'hombre'])
min_salario_mujeres <- min(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'mujer'])
min_salario_hombres <- min(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'hombre'])
max_salario_mujeres <- max(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'mujer'])
max_salario_hombres <- max(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'hombre'])
varianza_salario_mujeres <- var(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'mujer'])
varianza_salario_hombres <- var(BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'hombre'])

data_salarios <- data.frame(
  Sexo = c('mujer', 'hombre'),
  Media_Salario = c(media_salario_mujeres, media_salario_hombres),
  Min_Salario = c(min_salario_mujeres, min_salario_hombres),
  Max_Salario = c(max_salario_mujeres, max_salario_hombres),
  Varianza_Salario = c(varianza_salario_mujeres, varianza_salario_hombres)
)

```

```{r}
media_cuotas_mujeres <- mean(BaseSalarios$Coutas[BaseSalarios$Sexo == 'mujer'])
media_cuotas_hombres <- mean(BaseSalarios$Coutas[BaseSalarios$Sexo == 'hombre'])
min_cuotas_mujeres <- min(BaseSalarios$Coutas[BaseSalarios$Sexo == 'mujer'])
min_cuotas_hombres <- min(BaseSalarios$Coutas[BaseSalarios$Sexo == 'hombre'])
max_cuotas_mujeres <- max(BaseSalarios$Coutas[BaseSalarios$Sexo == 'mujer'])
max_cuotas_hombres <- max(BaseSalarios$Coutas[BaseSalarios$Sexo == 'hombre'])
varianza_cuotas_mujeres <- var(BaseSalarios$Coutas[BaseSalarios$Sexo == 'mujer'])
varianza_cuotas_hombres <- var(BaseSalarios$Coutas[BaseSalarios$Sexo == 'hombre'])

data_cuotas <- data.frame(
  Sexo = c('mujer', 'hombre'),
  Media_cuotas = c(media_cuotas_mujeres, media_cuotas_hombres),
  Min_cuotas = c(min_cuotas_mujeres, min_cuotas_hombres),
  Max_cuotas = c(max_cuotas_mujeres, max_cuotas_hombres),
  Varianza_cuotas = c(varianza_cuotas_mujeres, varianza_cuotas_hombres)
)
```

```{r}
# Filtrar los datos solo para mujeres
data_mujeres <- BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'mujer']

# Crear un boxplot con ggplot2
p1 <- ggplot(data.frame(salario = data_mujeres), aes( x= salario)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", width = 0.5) +
  theme_minimal() +  # Utilizar un tema minimalista
  labs(title = "Boxplot del Salario para Mujeres",
       x = "Salario",
       y = "") +
  theme_few() + # Utilizar un tema adicional de ggthemes para mejorar la apariencia
  scale_x_continuous()

# Mostrar el gráfico
print(p1)

# Filtrar los datos solo para mujeres
data_hombres <- BaseSalarios$`U. Salario`[BaseSalarios$Sexo == 'hombre']

# Crear un boxplot con ggplot2
p2 <- ggplot(data.frame(salario = data_hombres), aes(x = salario)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", width = 0.5) +
  theme_minimal() +  # Utilizar un tema minimalista
  labs(title = "Boxplot del Salario para Hombres",
       x = "Salario",
       y = "") +
  theme_few() + # Utilizar un tema adicional de ggthemes para mejorar la apariencia
  scale_y_continuous()

# Mostrar el gráfico
print(p2)



```

```{r}
# Boxplot por grupo
ggplot(data = BaseSalarios, aes(x = Sexo, y = `U. Salario`)) +
       stat_boxplot(geom = "errorbar", # Bigotes
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE", colour = "#1F3552", # Colores
                    alpha = 0.9, outlier.colour = "red") +
       scale_y_log10(name = "Salario") +  # Etiqueta de la variable continua
       scale_x_discrete(name = "Sexo") +        # Etiqueta de los grupos
       ggtitle("Boxplot por grupos en ggplot2") +       # Título del plot
       theme(axis.line = element_line(colour = "black", # Personalización del tema
                                      size = 0.25)) + theme_few()

```
```{r}
t.test(BaseSalarios$Coutas[BaseSalarios$Sexo == 'mujer'],BaseSalarios$Coutas[BaseSalarios$Sexo == 'hombre'])
```

```{r}
#Pregunta #2
m<-ggplot(BaseSalarios, aes(x = `U. Salario`)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Your Column", x = "Salarios", y = "Frecuencia")

show(m)
```
```{r}
D=density(BaseSalarios$`U. Salario`,kernel="rectangular")

#hist(BaseSalarios$`U. Salario`, main="DistribucionAsaltos-KernelUniforme", freq=FALSE) lines(D,lwd=2,lty=1,col ="blue")

ggplot(BaseSalarios, aes(x = `U. Salario`)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 1.5) + geom_line(D,lwd=2,lty=1,col ="blue") + 
  labs(title = "Histogram of Your Column", x = "Salarios", y = "Frecuencia")

ggplot(BaseSalarios, aes(x = `U. Salario`)) + geom_density(D, )

ggplot(data = BaseSalarios, aes(x = `U. Salario`)) +
  geom_density(fill = "skyblue", color = "black", alpha = 0.7) +
  ggtitle("Density Plot") +
  xlab("Values") +
  ylab("Density")

d<-ggplot(data = BaseSalarios, aes(x = `U. Salario`)) + 
  geom_histogram(binwidth = 1, fill = "blue", color = "lightblue", alpha = 0.7) +
  geom_density(bw = "nrd0", kernel='rectangular', color = "black", alpha = 0.7) +
  geom_density(bw = "nrd0", kernel='biweight',  color = "lightblue", alpha = 0.7) +
  geom_density(bw = "nrd0",kernel='gaussian', color = "yellow", alpha = 0.7)+
  geom_density(bw = "nrd0",kernel='epanechnikov', color = "red", alpha = 0.7) +
  geom_density(bw = "nrd0", kernel='triangular', color = "pink", alpha = 0.7) +
  geom_density(bw = "nrd0", kernel='cosine', color = "lightgreen", alpha = 0.7) 

show(d)

```

